name: sym-learn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - tensorboard
  - music21==9.1.0
  - pip==23.0.1
  - pip:
      - miditok==3.0.1
      - symusic==0.3.5
      - tokenizers==0.15.2
