name: sym-learn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch==2.1.2
  - torchvision==0.16.2
  - torchaudio==2.1.2
  - pytorch-cuda=11.8
  - tensorboard
  - music21==9.1.0
  - pip==23.0.1
  - pip:
      - miditok==3.0.1
      - symusic==0.3.5
      - tokenizers==0.15.2
